FROM node:18-alpine AS build
WORKDIR /app
COPY ./services/dashboard/package*.json ./
RUN npm install
COPY ./services/dashboard/ ./

RUN npm run build


FROM nginx:alpine
# Copiamos los archivos generados en la etapa de construcción a la carpeta de Nginx
COPY --from=build /app/build /usr/share/nginx/html
# No necesitamos un nginx.conf personalizado a menos que quieras manejar rutas específicas
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]